version: '2'
services:
#    vice-db:
#        image: cha87de/couchbase-cloudnative
#        environment:
#         - CLUSTER=localhost
#         - USER=admin
#         - PASS=secret
#         - PORT=8091
#         - RAMSIZEMB=2048
#         - RAMSIZEINDEXMB=512
#         - RAMSIZEFTSMB=512
#         - BUCKETS=
#         - BUCKETSIZES=
#         - AUTOREBALANCE=true
#         - RETRIES_INIT=50
#        volumes:
#         - /srv/vice/couchbase:/opt/couchbase/var/
    vice-db:
        image: kallqvist/rethinkdb-cluster
        environment:
         - JOIN=vice-db
        volumes:
         - /srv/vice/vice-db:/data
    vice-mq:
        image: rabbitmq:management
        environment:
         - RABBITMQ_DEFAULT_USER=vice
         - RABBITMQ_DEFAULT_PASS=secret
    vice-api:
        image: viceregistry/vice-api
        restart: on-failure
        ports:
         - 8080:8080
        environment:
         - PORT=8080
         - RETHINKDB_LOCATION=vice-db
         - RETHINKDB_DATABASE=vice
         - RABBITMQ_LOCATION=vice-mq
         - RABBITMQ_USER=vice
         - RABBITMQ_PASS=secret
        depends_on:
         - vice-db
         - vice-mq
    vice-import:
        image: viceregistry/vice-worker
        restart: on-failure
        environment:
         - WORKERTYPE=import
         - RETHINKDB_LOCATION=vice-db
         - RETHINKDB_DATABASE=vice
         - RABBITMQ_LOCATION=vice-mq
         - RABBITMQ_USER=vice
         - RABBITMQ_PASS=secret
        depends_on:
         - vice-db
         - vice-mq
         - vice-store
    vice-export:
        image: viceregistry/vice-worker
        restart: on-failure
        environment:
         - WORKERTYPE=export
         - RETHINKDB_LOCATION=vice-db
         - RETHINKDB_DATABASE=vice
         - RABBITMQ_LOCATION=vice-mq
         - RABBITMQ_USER=vice
         - RABBITMQ_PASS=secret
        depends_on:
         - vice-db
         - vice-mq
         - vice-store
    vice-store:
        image: viceregistry/vice-store
        restart: on-failure
        environment:
         - RETHINKDB_LOCATION=vice-db
         - RETHINKDB_DATABASE=vice
         - RABBITMQ_LOCATION=vice-mq
         - RABBITMQ_USER=vice
         - RABBITMQ_PASS=secret
         - STORAGE_BASEPATH=/opt/images/
        volumes:
         - /srv/vice/images:/opt/images
        depends_on:
         - vice-db
         - vice-mq
    vice-webui:
        image: viceregistry/vice-webui
        restart: on-failure
        ports:
         - 8081:80
        depends_on:
         - vice-api
